---
name : Docker Build and Push to AWS ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }} # globalrmi-vpis/vpis-x-process
      DOCKERFILE_TEMPLATE: ${{ vars.DOCKERFILE_TEMPLATE || 'Dockerfile.tpl' }}
      DOCKER_BASE_IMAGE: ${{ vars.DOCKER_BASE_IMAGE || 'public.ecr.aws/lambda/python:latest' }}
      SRC_PATH: ${{ vars.SRC_PATH || './src/' }}
      LAMBDA_HANDLER: ${{ vars.LAMBDA_HANDLER || 'lambda.lambda_handler' }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        id: credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get Caller Identity
        id: caller-identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR Repository
        id: ecr-create-repo
        run: >
          aws ecr create-repository
          --repository-name $ECR_REPOSITORY || true

      - name: Get version from VERSION file
        id: version
        run: |
          if [ ! -f VERSION ]; then
            echo "VERSION file not found.  Exiting..."
            exit 1
          fi
          VERSION=$(cat VERSION)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" | tee -a $GITHUB_OUTPUT

      - name: Process Dockerfile template
        id: process-dockerfile
        run: |
          if [ ! -f ${{ env.DOCKERFILE_TEMPLATE }} ] ; then
            echo "${{ env.DOCKERFILE_TEMPLATE }} file not found.  Exiting..."
            exit 1
          fi
          read -r TEMPLATE < ${{ env.DOCKERFILE_TEMPLATE }}
          eval OUTPUT="\"$TEMPLATE\""
          echo $OUTPUT > Dockerfile
          echo "---------------------"
          echo "Dockerfile generated:"
          echo "---------------------"
          cat Dockerfile

      - name: Docker Build
        id: docker-build
        env:
          BUILD_VERSION: ${{ steps.version.outputs.VERSION }}
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: >
          docker build
          --tag ${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_VERSION}
          .

      - name: Docker Tag with Semantic Version
        id: docker-tag
        env:
          BUILD_VERSION: ${{ steps.version.outputs.VERSION }}
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: >
          docker tag
          ${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_VERSION}
          ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest

      - name: Docker Push
        id: docker-push
        env:
          BUILD_VERSION: ${{ steps.version.outputs.VERSION }}
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: >
          docker push
          ${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_VERSION}
...